// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package server

const (
	Petstore_authScopes = "petstore_auth.Scopes"
)

// Defines values for CommentRequestParentType.
const (
	CommentRequestParentTypeComment CommentRequestParentType = "comment"

	CommentRequestParentTypePost CommentRequestParentType = "post"
)

// CommentRequest defines model for CommentRequest.
type CommentRequest struct {
	Content  string `json:"content"`
	ParentId string `json:"parent_id"`

	// type of the parent in which this comment belongs to
	ParentType CommentRequestParentType `json:"parent_type"`
}

// type of the parent in which this comment belongs to
type CommentRequestParentType string

// CommentResponse defines model for CommentResponse.
type CommentResponse struct {
	AuthorId *string `json:"author_id,omitempty"`

	// comment of this comment
	CommentList *[]CommentResponse `json:"comment_list,omitempty"`
	Content     *string            `json:"content,omitempty"`
	ParentId    *string            `json:"parent_id,omitempty"`

	// type of the parent in which this comment belongs to
	ParentType *string `json:"parent_type,omitempty"`
}

// PostRequest defines model for PostRequest.
type PostRequest struct {
	Content string  `json:"content"`
	Name    *string `json:"name,omitempty"`
}

// PostResponse defines model for PostResponse.
type PostResponse struct {
	Content *string `json:"content,omitempty"`
	Id      *int64  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// Response for multiple post
type PostsResponse []PostResponse

// User defines model for User.
type User struct {
	Email     *string `json:"email,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	Id        *int64  `json:"id,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Password  *string `json:"password,omitempty"`
	Phone     *string `json:"phone,omitempty"`

	// User Status
	UserStatus *int32  `json:"userStatus,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// CommentId defines model for commentId.
type CommentId string

// PostId defines model for postId.
type PostId string

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody User

// LoginUserParams defines parameters for LoginUser.
type LoginUserParams struct {
	// The user name for login
	Username *string `json:"username,omitempty"`

	// The password for login in clear text
	Password *string `json:"password,omitempty"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody User

// PostV1CommentJSONBody defines parameters for PostV1Comment.
type PostV1CommentJSONBody CommentRequest

// AddPostJSONBody defines parameters for AddPost.
type AddPostJSONBody PostRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// PostV1CommentJSONRequestBody defines body for PostV1Comment for application/json ContentType.
type PostV1CommentJSONRequestBody PostV1CommentJSONBody

// AddPostJSONRequestBody defines body for AddPost for application/json ContentType.
type AddPostJSONRequestBody AddPostJSONBody
